name: mirror-cncf-repos

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 3 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache cncf-zsh
        id: cache-primes
        uses: actions/cache@v3
        with:
          path: cncf
          key: cncf-mirrors

      - name: Init mirror repos
        if: steps.cache-primes.outputs.cache-hit != 'true'
        run: bash init-cncf.sh

      - name: Mirror repos
        if: steps.cache-primes.outputs.cache-hit == 'true'
        run: |
          git config --global credential.helper store
          echo ${{ secrets.CODING_GITHUB_ACTION }} > ~/.git-credentials
          WORK_DIR=$(pwd)
          for dir in cncf/*; do
            cd $dir && pwd
            git remote update origin
            git push mirror --tags --prune --force
            git push mirror --all --prune --force
            cd $WORK_DIR
          done
